#!/bin/bash

#PBS -N get_geckos
#PBS -l select=1:ncpus=1:mem=16gb
#PBS -l walltime=10:00:00
#PBS -M f.pal@unsw.edu.au
#PBS -m bae
#PBS -j oe
#PBS -o ../reports/output_reports
#PBS -e ../reports/error_reports

#PBS -J 0-100
## ${PBS_ARRAY_INDEX}

cd $PBS_O_WORKDIR
source ../my_env/bin/activate 

python3 ../src/geckos_count.py --simulation=m12i --galaxy=NGC3957 --location=katana --iteration=${PBS_ARRAY_INDEX}
